name: langgraph-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langgraph
    - langchain-core
    - langchain-openai
    - langchain-community
    - jupyterlab
    - tiktoken
    - pydantic==1.10.13
    - python-dotenv
    - tavily-python
    